name: demo_structure
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.8.0+1
  retrofit: ^4.4.2

  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  bloc_concurrency: ^0.3.0

  go_router: ^15.0.0

  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  flutter_spinkit: ^5.2.1
  pull_to_refresh: ^2.0.0
  cupertino_icons: ^1.0.6
  dropdown_button2: ^2.3.9

  flutter_local_notifications: ^19.1.0

  url_launcher: ^6.3.1
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.3.0
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  intl: any
  logger: ^2.5.0
  image_picker: ^1.1.2
  toastification: ^3.0.1
  fluttertoast: ^8.2.12

  flutter_native_splash: ^2.4.1
  flutter_date_pickers: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/languages/

